# Generated by Django 3.2 on 2021-05-22 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.CharField(max_length=265)),
                ('status', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=265)),
                ('condition', models.CharField(choices=[('Brand New', 'Brand New'), ('Open Box', 'Open Box'), ('Used', 'Used'), ('Not Working', 'Not Working')], max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=2048)),
            ],
        ),
    ]
