# Generated by Django 3.2 on 2021-05-23 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=12)),
                ('image', models.ImageField(upload_to='media/images')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poster', models.CharField(max_length=265)),
                ('code', models.CharField(max_length=12)),
                ('status', models.BooleanField(default=True)),
                ('title', models.CharField(max_length=265)),
                ('condition', models.CharField(choices=[('Brand New', 'Brand New'), ('Open Box', 'Open Box'), ('Used', 'Used'), ('Not Working', 'Not Working')], max_length=128)),
                ('location', models.CharField(max_length=128)),
                ('description', models.CharField(max_length=2048)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=32)),
                ('name', models.CharField(max_length=32)),
                ('email', models.CharField(max_length=32, null=True)),
            ],
        ),
    ]
